export const ROOM_QUESTS = {
  "Recepção": {
    name: "Recepção",
    description: "A porta de entrada para o caos do Hospital Fumegator.",
    quests: [
      {
        id: "reception_common_1",
        difficulty: "Common",
        title: "Boas-vindas ao Caos",
        narrative: "Um novo paciente chegou e está causando alvoroço na recepção. Ajude a acalmá-lo e a preencher seus dados de internação.",
        rewards: { xp: 50, coins: 10, items: [] },
        requirements: { level: 1, class: null },
      },
      {
        id: "reception_uncommon_1",
        difficulty: "Uncommon",
        title: "O Mistério do Paciente Desaparecido",
        narrative: "Um paciente da recepção sumiu misteriosamente. Investigue os arredores e encontre pistas sobre seu paradeiro.",
        rewards: { xp: 100, coins: 25, items: [{ id: "small_medkit", quantity: 1 }] },
        requirements: { level: 3, class: null },
      },
      {
        id: "reception_rare_1",
        difficulty: "Rare",
        title: "A Fuga em Massa",
        narrative: "Vários pacientes conseguiram escapar da recepção. Você precisa contê-los antes que causem mais problemas na cidade.",
        rewards: { xp: 200, coins: 50, items: [{ id: "medium_medkit", quantity: 1 }, { id: "rare_material_a", quantity: 1 }] },
        requirements: { level: 5, class: "Therapist" },
      },
      {
        id: "reception_epic_1",
        difficulty: "Epic",
        title: "O Agente Infiltrado",
        narrative: "Há rumores de um agente infiltrado na recepção, tentando sabotar as operações do hospital. Identifique-o e neutralize a ameaça.",
        rewards: { xp: 400, coins: 100, items: [{ id: "large_medkit", quantity: 1 }, { id: "epic_material_b", quantity: 1 }] },
        requirements: { level: 8, class: "Researcher" },
      },
      {
        id: "reception_legendary_1",
        difficulty: "Legendary",
        title: "O Portal Dimensional",
        narrative: "Um portal dimensional se abriu na recepção, trazendo criaturas de outra dimensão. Feche o portal e salve o hospital da invasão.",
        rewards: { xp: 800, coins: 200, items: [{ id: "legendary_key_reception", quantity: 1 }, { id: "unique_artifact_c", quantity: 1 }] },
        requirements: { level: 10, class: "Surgeon" },
      },
    ],
  },
  "Consultório Médico": {
    name: "Consultório Médico",
    description: "Onde os diagnósticos são feitos e os mistérios da saúde são desvendados.",
    quests: [
      {
        id: "consultorio_common_1",
        difficulty: "Common",
        title: "Diagnóstico Urgente",
        narrative: "Um paciente com sintomas estranhos precisa de um diagnóstico rápido. Analise os dados e encontre a cura.",
        rewards: { xp: 60, coins: 15, items: [] },
        requirements: { level: 1, class: null },
      },
      {
        id: "consultorio_uncommon_1",
        difficulty: "Uncommon",
        title: "A Praga Inesperada",
        narrative: "Uma doença desconhecida está se espalhando pelo consultório. Isole os pacientes e encontre a origem da infecção.",
        rewards: { xp: 120, coins: 30, items: [{ id: "antivirus_dose", quantity: 1 }] },
        requirements: { level: 3, class: "Researcher" },
      },
      {
        id: "consultorio_rare_1",
        difficulty: "Rare",
        title: "O Paciente Possuído",
        narrative: "Um paciente parece estar possuído por uma entidade. Realize um exorcismo médico para libertá-lo.",
        rewards: { xp: 250, coins: 60, items: [{ id: "holy_water", quantity: 1 }, { id: "rare_material_c", quantity: 1 }] },
        requirements: { level: 6, class: "Therapist" },
      },
      {
        id: "consultorio_epic_1",
        difficulty: "Epic",
        title: "A Conspiração Farmacêutica",
        narrative: "Descubra uma conspiração envolvendo medicamentos falsificados sendo distribuídos no consultório. Exponha os culpados.",
        rewards: { xp: 500, coins: 120, items: [{ id: "truth_serum", quantity: 1 }, { id: "epic_material_d", quantity: 1 }] },
        requirements: { level: 9, class: "Pharmacist" },
      },
      {
        id: "consultorio_legendary_1",
        difficulty: "Legendary",
        title: "A Cura Universal",
        narrative: "Uma doença incurável assola o mundo. No consultório, você encontra a chave para a cura universal. Proteja-a e salve a humanidade.",
        rewards: { xp: 1000, coins: 250, items: [{ id: "legendary_key_consultorio", quantity: 1 }, { id: "universal_cure_formula", quantity: 1 }] },
        requirements: { level: 12, class: "Surgeon" },
      },
    ],
  },
  "Laboratório": {
    name: "Laboratório",
    description: "O coração da pesquisa e desenvolvimento, onde novas descobertas são feitas.",
    quests: [
      {
        id: "laboratorio_common_1",
        difficulty: "Common",
        title: "Análise de Amostras",
        narrative: "Analise uma série de amostras biológicas para identificar um patógeno comum.",
        rewards: { xp: 70, coins: 20, items: [] },
        requirements: { level: 2, class: null },
      },
      {
        id: "laboratorio_uncommon_1",
        difficulty: "Uncommon",
        title: "Experimento Descontrolado",
        narrative: "Um experimento deu errado e um mutagênico está se espalhando. Contenha-o antes que afete todo o hospital.",
        rewards: { xp: 150, coins: 35, items: [{ id: "stabilizer_agent", quantity: 1 }] },
        requirements: { level: 4, class: "Researcher" },
      },
      {
        id: "laboratorio_rare_1",
        difficulty: "Rare",
        title: "A Fórmula Perdida",
        narrative: "Uma fórmula secreta de um poderoso medicamento foi perdida no laboratório. Encontre-a e evite que caia em mãos erradas.",
        rewards: { xp: 300, coins: 70, items: [{ id: "decryption_key", quantity: 1 }, { id: "rare_material_d", quantity: 1 }] },
        requirements: { level: 7, class: "Pharmacist" },
      },
      {
        id: "laboratorio_epic_1",
        difficulty: "Epic",
        title: "A Invasão Cibernética",
        narrative: "Hackers invadiram os sistemas do laboratório, tentando roubar dados confidenciais. Defenda a rede e expulse os invasores.",
        rewards: { xp: 600, coins: 150, items: [{ id: "firewall_upgrade", quantity: 1 }, { id: "epic_material_e", quantity: 1 }] },
        requirements: { level: 10, class: "Surgeon" },
      },
      {
        id: "laboratorio_legendary_1",
        difficulty: "Legendary",
        title: "A Criação da Vida Artificial",
        narrative: "Você está prestes a concluir a criação de uma forma de vida artificial no laboratório. Proteja seu trabalho de forças externas que desejam roubá-lo.",
        rewards: { xp: 1200, coins: 300, items: [{ id: "legendary_key_laboratorio", quantity: 1 }, { id: "artificial_life_core", quantity: 1 }] },
        requirements: { level: 14, class: "Researcher" },
      },
    ],
  },
  "Enfermaria": {
    name: "Enfermaria",
    description: "Onde os pacientes se recuperam... ou não.",
    quests: [
      {
        id: "enfermaria_common_1",
        difficulty: "Common",
        title: "Ronda Noturna",
        narrative: "Faça a ronda noturna na enfermaria, verificando o estado dos pacientes e garantindo que todos estejam confortáveis.",
        rewards: { xp: 40, coins: 8, items: [] },
        requirements: { level: 1, class: null },
      },
      {
        id: "enfermaria_uncommon_1",
        difficulty: "Uncommon",
        title: "O Paciente Sonâmbulo",
        narrative: "Um paciente sonâmbulo está perambulando pela enfermaria. Leve-o de volta para a cama sem acordá-lo.",
        rewards: { xp: 80, coins: 20, items: [{ id: "sleeping_pill", quantity: 1 }] },
        requirements: { level: 2, class: "Therapist" },
      },
      {
        id: "enfermaria_rare_1",
        difficulty: "Rare",
        title: "A Infestação de Pragas",
        narrative: "A enfermaria foi infestada por pragas. Elimine-as e garanta a higiene do local.",
        rewards: { xp: 180, coins: 40, items: [{ id: "insecticide", quantity: 1 }, { id: "rare_material_e", quantity: 1 }] },
        requirements: { level: 4, class: "Pharmacist" },
      },
      {
        id: "enfermaria_epic_1",
        difficulty: "Epic",
        title: "O Motim dos Pacientes",
        narrative: "Os pacientes da enfermaria iniciaram um motim. Restabeleça a ordem e acalme os ânimos.",
        rewards: { xp: 350, coins: 80, items: [{ id: "tranquilizer_darts", quantity: 1 }, { id: "epic_material_f", quantity: 1 }] },
        requirements: { level: 7, class: "Surgeon" },
      },
      {
        id: "enfermaria_legendary_1",
        difficulty: "Legendary",
        title: "A Ressurreição dos Mortos",
        narrative: "Os mortos na enfermaria estão se levantando. Você deve detê-los antes que o hospital seja dominado por zumbis.",
        rewards: { xp: 700, coins: 180, items: [{ id: "legendary_key_enfermaria", quantity: 1 }, { id: "zombie_antidote", quantity: 1 }] },
        requirements: { level: 9, class: "Researcher" },
      },
    ],
  },
  "Centro Cirúrgico": {
    name: "Centro Cirúrgico",
    description: "Onde a vida e a morte se encontram sob o bisturi.",
    quests: [
      {
        id: "cirurgico_common_1",
        difficulty: "Common",
        title: "Instrumentos Esterilizados",
        narrative: "Prepare os instrumentos cirúrgicos para uma operação de rotina, garantindo a esterilização completa.",
        rewards: { xp: 80, coins: 20, items: [] },
        requirements: { level: 3, class: null },
      },
      {
        id: "cirurgico_uncommon_1",
        difficulty: "Uncommon",
        title: "Cirurgia de Emergência",
        narrative: "Um paciente chegou em estado crítico. Realize uma cirurgia de emergência para salvar sua vida.",
        rewards: { xp: 180, coins: 45, items: [{ id: "adrenaline_shot", quantity: 1 }] },
        requirements: { level: 5, class: "Surgeon" },
      },
      {
        id: "cirurgico_rare_1",
        difficulty: "Rare",
        title: "O Órgão Alienígena",
        narrative: "Durante uma cirurgia, um órgão de origem alienígena é descoberto. Remova-o com segurança e estude-o.",
        rewards: { xp: 350, coins: 80, items: [{ id: "alien_organ_sample", quantity: 1 }, { id: "rare_material_f", quantity: 1 }] },
        requirements: { level: 8, class: "Researcher" },
      },
      {
        id: "cirurgico_epic_1",
        difficulty: "Epic",
        title: "O Vírus Mortal",
        narrative: "Um vírus mortal foi liberado no centro cirúrgico. Contenha a contaminação e encontre uma vacina antes que seja tarde demais.",
        rewards: { xp: 700, coins: 180, items: [{ id: "antiviral_vaccine", quantity: 1 }, { id: "epic_material_g", quantity: 1 }] },
        requirements: { level: 11, class: "Pharmacist" },
      },
      {
        id: "cirurgico_legendary_1",
        difficulty: "Legendary",
        title: "A Fusão de Consciências",
        narrative: "Um experimento de fusão de consciências deu errado no centro cirúrgico. Separe as mentes antes que elas se destruam mutuamente.",
        rewards: { xp: 1500, coins: 400, items: [{ id: "legendary_key_cirurgico", quantity: 1 }, { id: "consciousness_separator", quantity: 1 }] },
        requirements: { level: 15, class: "Therapist" },
      },
    ],
  },
  "UTI": {
    name: "UTI",
    description: "Unidade de Terapia Intensiva, onde os casos mais graves lutam pela vida.",
    quests: [
      {
        id: "uti_common_1",
        difficulty: "Common",
        title: "Monitoramento Constante",
        narrative: "Monitore os sinais vitais dos pacientes na UTI e garanta que todos os equipamentos estejam funcionando corretamente.",
        rewards: { xp: 90, coins: 25, items: [] },
        requirements: { level: 4, class: null },
      },
      {
        id: "uti_uncommon_1",
        difficulty: "Uncommon",
        title: "A Crise Cardíaca",
        narrative: "Um paciente sofreu uma parada cardíaca na UTI. Use suas habilidades para reanimá-lo.",
        rewards: { xp: 200, coins: 50, items: [{ id: "defibrillator_charge", quantity: 1 }] },
        requirements: { level: 6, class: "Surgeon" },
      },
      {
        id: "uti_rare_1",
        difficulty: "Rare",
        title: "O Pesadelo Induzido",
        narrative: "Pacientes na UTI estão tendo pesadelos terríveis. Descubra a causa e acabe com o sofrimento.",
        rewards: { xp: 400, coins: 90, items: [{ id: "dream_catcher", quantity: 1 }, { id: "rare_material_g", quantity: 1 }] },
        requirements: { level: 9, class: "Therapist" },
      },
      {
        id: "uti_epic_1",
        difficulty: "Epic",
        title: "A Falha no Suporte de Vida",
        narrative: "Os sistemas de suporte de vida da UTI estão falhando. Repare-os rapidamente para evitar uma catástrofe.",
        rewards: { xp: 800, coins: 200, items: [{ id: "emergency_power_cell", quantity: 1 }, { id: "epic_material_h", quantity: 1 }] },
        requirements: { level: 12, class: "Researcher" },
      },
      {
        id: "uti_legendary_1",
        difficulty: "Legendary",
        title: "A Consciência Coletiva",
        narrative: "Os pacientes da UTI estão se conectando em uma consciência coletiva. Desfaça a conexão antes que suas mentes se percam para sempre.",
        rewards: { xp: 1800, coins: 500, items: [{ id: "legendary_key_uti", quantity: 1 }, { id: "mind_separator", quantity: 1 }] },
        requirements: { level: 16, class: "Pharmacist" },
      },
    ],
  },
};

export const getQuestById = (questId) => {
  for (const room in ROOM_QUESTS) {
    const quest = ROOM_QUESTS[room].quests.find(q => q.id === questId);
    if (quest) return quest;
  }
  return null;
};

